# UID生成设置
uid:
  # 获得随机UID的玩家数量 (1-100)
  random-allocation-count: 100
  # 随机UID范围 (必须在1-9999之间)
  random-min: 1
  random-max: 100
  # 顺序UID的起始数字 (必须大于random-max)
  sequential-start: 10000
  # UID格式设置
  format:
    # 显示的位数 (推荐: 4)
    digits: 4
    # 用于补位的字符 (推荐: "0")
    pad-char: "0"

# 数据库设置
database:
  url: "jdbc:mysql://localhost:3306/uidplugin?useSSL=false&allowPublicKeyRetrieval=true"
  username: "root"
  password: "password"
  pool-size: 10

# 性能设置
performance:
  # 缓存时长(分钟)
  cache-duration: 30
  # 最大缓存数量
  max-cache-size: 1000
  # 缓存清理间隔(分钟)
  cache-cleanup-interval: 15
  # 数据库连接池监控间隔(分钟)
  pool-health-check-interval: 30

# 消息 (支持使用&作为颜色代码)
messages:
  default-locale: "zh_CN"
  prefix: "&8[&6UID&8] &r"
  reload-messages: true  # 是否在重载插件时重新加载消息
  uid-info: "&a玩家 %player% 的UID是: &e%uid%"
  uid-not-found: "&c未找到该玩家的UID"
  uid-generated: "&a已为玩家 %player% 生成UID: &e%uid%"
  uid-generated-notify: "&a你的新UID是: &e%uid%"
  no-permission: "&c你没有权限使用此命令"
  player-required: "&c请指定玩家名"
  player-not-found: "&c未找到该玩家"
  error-generating: "&c生成UID时发生错误"
  stats-header: "&6=== 性能统计 ==="
  stats-line: "&7%operation%: &e%avg%ms &7(次数: &e%count%&7)"

# 性能监控设置
monitoring:
  # 是否启用详细性能监控
  enabled: true
  # 性能数据采样数量
  max-samples: 1000
  # 警告阈值(毫秒)
  warning-threshold: 50
  # 自动重置统计间隔(分钟)
  reset-interval: 60 